### ISSUE TITLE
"incompatible character encodings" error with Ruby 2.0

### ISSUE THREAD

**Issue by badboy** [jewel/clearskies#11]
```
$ ./clearskies debug
....
control_connection> Control error: incompatible character encodings: UTF-8 and ASCII-8BIT
control_connection> /home/badboy/code/clearskies/lib/access_code.rb:59:in `to_s'
/home/badboy/code/clearskies/lib/control_server.rb:115:in `handle_command'
/home/badboy/code/clearskies/lib/control_server.rb:59:in `block in serve'
/home/badboy/code/clearskies/lib/control_server.rb:53:in `loop'
/home/badboy/code/clearskies/lib/control_server.rb:53:in `serve'
/home/badboy/code/clearskies/lib/control_server.rb:40:in `block (2 levels) in run'
/home/badboy/code/clearskies/lib/simple_thread.rb:72:in `block (2 levels) in initialize'
/home/badboy/code/clearskies/lib/simple_thread.rb:38:in `glock'
/home/badboy/code/clearskies/lib/simple_thread.rb:70:in `block in initialize'
```

```
$ ./clearskies share $(pwd)/shared read-write
/home/badboy/code/clearskies/lib/control_client.rb:24:in `issue': server can't :create_access_code, says: Encoding::CompatibilityError incompatible character encodings: UTF-8 and ASCII-8BIT (RuntimeError)
    from ./clearskies:143:in `<main>'
```

In Ruby 2.0 the default encoding is UTF-8 for all files (if not specified differently). This way access_code fails expecting ASCII-8BIT where it is UTF-8.
You should specifiy that you're handling binary data.

**Comment by jewel** [comment]
Thanks for the report.  I've been developing against 1.9, so there will probably be lots of other problems with ruby 2.0.  I'll look into getting the unit tests and the read-write integration test to run against ruby 2.0 in the next few days.

**Comment by jewel** [comment]
I don't see any more 2.0 issues.  Please open more issues if you find any.

**Comment by badboy** [comment]
Great, I will play with Clearskies, let's see how it works so far.
